import React, { useState } from "react";
import { FileText, Download, Calendar, Filter, Search, ArrowRight, CheckCircle, Clock } from "lucide-react";
import { cn } from "../lib/utils";

const REPORT_TEMPLATES = [
  { id: "daily_ops", title: "Daily Operations Report", description: "Summary of today's telemetry, alarms, and communication status.", icon: FileText, color: "bg-blue-600" },
  { id: "weekly_leak", title: "Weekly Leak-Risk Report", description: "Analysis of multi-day trends to identify potential water loss.", icon: CheckCircle, color: "bg-green-600" },
  { id: "battery_maint", title: "Battery Maintenance Report", description: "Forecast of battery replacement needs across the fleet.", icon: Clock, color: "bg-orange-600" },
  { id: "alarm_kpi", title: "Alarm KPI Report", description: "SLA tracking and response time metrics for active alerts.", icon: FileText, color: "bg-red-600" },
];

export default function Reports() {
  const [loading, setLoading] = useState(false);

  const handleGenerate = (id: string) => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      alert(`Report ${id} generated successfully! Check your downloads.`);
    }, 1500);
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-zinc-900 italic serif">Reports & Exports</h1>
          <p className="text-zinc-500 text-sm">Business and compliance reporting for your water network.</p>
        </div>
        <div className="flex items-center gap-2">
          <button className="bg-zinc-100 text-zinc-900 border border-zinc-200 px-4 py-2 rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-zinc-200 transition-all flex items-center gap-2">
            <Calendar className="h-4 w-4" />
            Schedule Delivery
          </button>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {REPORT_TEMPLATES.map((report) => (
          <div key={report.id} className="bg-white rounded-xl border border-zinc-200 p-6 shadow-sm hover:shadow-md transition-shadow group">
            <div className="flex items-start justify-between mb-6">
              <div className={cn("p-3 rounded-xl text-white shadow-lg", report.color)}>
                <report.icon size={24} />
              </div>
              <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                <Clock className="h-3 w-3" />
                Last: 2026-03-29
              </div>
            </div>
            <h3 className="text-lg font-bold text-zinc-900 mb-2 italic serif">{report.title}</h3>
            <p className="text-sm text-zinc-500 mb-6 leading-relaxed">{report.description}</p>
            <div className="flex items-center gap-3">
              <button 
                onClick={() => handleGenerate(report.id)}
                disabled={loading}
                className="flex-1 bg-zinc-900 text-white py-3 rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-zinc-800 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {loading ? "Generating..." : <><Download className="h-4 w-4" /> Generate CSV</>}
              </button>
              <button className="p-3 bg-zinc-100 text-zinc-600 rounded-lg hover:bg-zinc-200 transition-all" title="View PDF">
                <FileText size={18} />
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-zinc-50 rounded-xl border border-zinc-200 p-8">
        <h3 className="text-sm font-bold uppercase tracking-widest mb-6 italic serif text-zinc-500">Recent Generated Reports</h3>
        <div className="space-y-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="bg-white p-4 rounded-lg border border-zinc-200 flex items-center justify-between hover:bg-zinc-50 transition-colors">
              <div className="flex items-center gap-4">
                <div className="p-2 bg-zinc-100 rounded text-zinc-500">
                  <FileText size={20} />
                </div>
                <div>
                  <div className="text-sm font-bold text-zinc-900 italic serif">Daily_Ops_Report_2026-03-2{9-i}.csv</div>
                  <div className="text-[10px] uppercase tracking-widest font-bold text-zinc-400">Generated by Admin • 2.4 MB</div>
                </div>
              </div>
              <button className="text-primary hover:underline text-xs font-bold uppercase tracking-widest">Download</button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
